### ISSUE TITLE
"keywords" should be associative with connected items

### ISSUE THREAD

**Issue by jketreno** [Board-Explorer/board-viewer#34]
If you go to the "i2c" keyword view of the [Quark D2000: I2C](https://board-explorer.github.io/board-explorer/#quark_mcu_dev_kit_d2000/I2C) you see the following:

![image](https://user-images.githubusercontent.com/742584/30493507-318b220e-99f9-11e7-9c3b-821f97d9088e.png)

However if you explicitly load [those two pins](https://board-explorer.github.io/board-explorer/#quark_mcu_dev_kit_d2000/J3PIN10,J3PIN9), it shows the connected pins:

![image](https://user-images.githubusercontent.com/742584/30493524-3c66752a-99f9-11e7-8a8d-431b083efb67.png)

Even though I2C is only tagged on pins 9 and 10, I expected to see the related pins highlighted as well.

@juliocri What do you think?

**Comment by juliocri** [comment]
@jketreno yeah! it seems that the related/connected are already set in the components, but the related/connected highlighting is only enabled with the direct interaction of the component(s) clicked,hovered or passed by the uri, not when you interact with keywords, I think we need to update the keyword highlighting functionality in order to review each refdes in the list and highlight the connected/related as well.. 

![screen shot 2017-09-18 at 10 13 49](https://user-images.githubusercontent.com/8356225/30549370-32a2fdde-9c5a-11e7-9990-8decc4930d67.png)


(According with the image above) is that the output expected for I2C?

**Comment by jketreno** [comment]
@juliocri I think that "connected" pins should transfer the keywords; however "related" pins should not. 

J12,J14,J16,J18 **should not** inherit the "I2C" from BMC150.

J8Pin10 **should** inherit "I2C" from J3Pin9.

**Comment by jketreno** [comment]
Looks good! Merged and published in board-viewer 0.0.35
